name: monpass
description: Une application sécurisée de gestion de mots de passe pour Android

# La version suit le modèle semver (major.minor.patch)
version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  
  
  # UI de base
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1           # Mise à jour
  
  # Stockage et sécurité
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4    # Mise à jour
  encrypt: ^5.0.3
  crypto: ^3.0.6
  local_auth: ^2.3.0
  
  # Réseaux et API
  http: ^1.4.0                      # Mise à jour
  connectivity_plus: ^6.1.4         # Mise à jour
  ssl_pinning_plugin: ^2.0.0
  
  # Sécurité supplémentaire
  root_check: ^0.0.2+1
  package_info_plus: ^8.3.0         # Mise à jour
  device_info_plus: ^11.4.0         # Mise à jour
  
  # Nouvelles dépendances
  flutter_dotenv: ^5.1.0            # Pour les variables d'environnement
  logger: ^2.0.2                    # Pour la journalisation
  path_provider: ^2.1.5             # Pour l'accès aux chemins de stockage
  intl: ^0.19.0                     # Pour le formatage des dates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0             # Mise à jour
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.6
  flutter_native_splash: ^2.3.6

# Configuration pour flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false  # Android uniquement
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#87CEEB"
  adaptive_icon_foreground: "assets/images/logo.png"

# Configuration pour flutter_native_splash
flutter_native_splash:
  color: "#87CEEB"
  image: "assets/images/logo.png"
  android_gravity: center
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#87CEEB"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env