name: monpass
description: Une application sécurisée de gestion de mots de passe pour Android

# La version suit le modèle semver (major.minor.patch)
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI de base
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.4.0           # Champ de saisie pour code PIN/OTP
  
  # Stockage et sécurité
  shared_preferences: ^2.1.0        # Stockage léger non sensible
  flutter_secure_storage: ^8.0.0    # Stockage sécurisé des données sensibles
  encrypt: ^5.0.1                   # Chiffrement AES
  crypto: ^3.0.3                    # Fonctions cryptographiques
  local_auth: ^2.1.6                # Authentification biométrique
  
  # Réseaux et API
  http: ^0.13.6                     # Requêtes HTTP
  connectivity_plus: ^4.0.1         # Vérification de la connectivité
  ssl_pinning_plugin: ^2.0.0        # Certificate pinning
  
  # Sécurité supplémentaire
  root_check: ^0.0.2+1              # Détection des appareils rootés
  package_info_plus: ^4.0.2         # Information sur le package pour vérification d'intégrité
  device_info_plus: ^8.1.0          # Information sur l'appareil pour détection d'émulateur

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1   # Pour générer facilement les icônes de l'application
  mockito: ^5.3.2                   # Pour les tests mockés
  flutter_native_splash: ^2.2.19    # Écran de démarrage natif

# Configuration pour flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false  # Android uniquement
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#87CEEB"
  adaptive_icon_foreground: "assets/images/logo.png"

# Configuration pour flutter_native_splash
flutter_native_splash:
  color: "#87CEEB"
  image: "assets/images/logo.png"
  android_gravity: center
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#87CEEB"
  fullscreen: true

flutter:
  uses-material-design: true

  # Déclaration des assets de l'application
  assets:
    - assets/images/